const initialState={eventMode:false,leave:[
 {id:'LV-1048',student:'Sonam Choden',sid:'12250018',course:'BSc CS · Year 2',date:'09 Sep',exit:'17:00',return:'20:00',destination:'Mongar Town',reason:'Purchase academic supplies',status:'Pending'},
 {id:'LV-1047',student:'Tenzin Dorji',sid:'12250041',course:'BSc IT · Year 3',date:'09 Sep',exit:'14:30',return:'18:30',destination:'Mongar Hospital',reason:'Medical appointment',status:'Pending'},
 {id:'LV-1046',student:'Pema Yangden',sid:'12250027',course:'BSc CS · Year 2',date:'09 Sep',exit:'16:00',return:'19:30',destination:'Lingmethang',reason:'Family matter',status:'Approved'},
 {id:'LV-1045',student:'Jigme Thinley',sid:'12250054',course:'BSc AI · Year 3',date:'09 Sep',exit:'13:00',return:'17:00',destination:'Gyelpozhing',reason:'Personal errand',status:'Rejected'},
 {id:'LV-1044',student:'Kezang Dema',sid:'12250009',course:'BSc IT · Year 1',date:'09 Sep',exit:'10:00',return:'15:30',destination:'Mongar Town',reason:'Bank work',status:'Outside'},
 {id:'LV-1043',student:'Namgay Wangchuk',sid:'12250063',course:'BSc CS · Year 4',date:'09 Sep',exit:'09:30',return:'14:00',destination:'Trashigang',reason:'Project field visit',status:'Overdue'}],
 gate:[{id:'GV-208',student:'Ugyen Lhamo',sid:'12250033',time:'10:18',result:'Manual',confidence:'62%',direction:'Exit'},{id:'GV-207',student:'Karma Tashi',sid:'12250072',time:'10:05',result:'Granted',confidence:'98%',direction:'Return'},{id:'GV-206',student:'Chimi Dema',sid:'12250021',time:'09:57',result:'Denied',confidence:'41%',direction:'Exit'}],
 visitors:[{id:'VS-319',name:'Dorji Wangmo',phone:'17 33 28 11',student:'Sonam Choden',sid:'12250018',relation:'Mother',purpose:'Family visit',entry:'09:42',exit:'—',status:'Inside'},{id:'VS-318',name:'Karma Rinchen',phone:'77 81 04 29',student:'Tenzin Dorji',sid:'12250041',relation:'Guardian',purpose:'Deliver documents',entry:'08:54',exit:'09:21',status:'Checked out'}],
 activities:[{title:'Exit verified',text:'Kezang Dema · 12250009',time:'8 min ago'},{title:'Visitor checked in',text:'Dorji Wangmo visiting Sonam Choden',time:'36 min ago'},{title:'Leave request submitted',text:'Tenzin Dorji · Medical appointment',time:'48 min ago'},{title:'Student marked overdue',text:'Namgay Wangchuk · expected 14:00',time:'1 hr ago'}]};
let state=JSON.parse(localStorage.getItem('campusx-state'))||initialState;let currentPage='dashboard';
const content=document.getElementById('content');
const save=()=>localStorage.setItem('campusx-state',JSON.stringify(state));
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');
const badge=s=>`<span class="badge ${s.toLowerCase().replace('checked out','returned')}">${s}</span>`;
const person=(n,id)=>`<div class="person"><span class="person-avatar">${initials(n)}</span><div><strong>${n}</strong><small>${id}</small></div></div>`;
function toast(msg,orange=false){const el=document.createElement('div');el.className='toast'+(orange?' orange':'');el.textContent=msg;document.getElementById('toastRoot').append(el);setTimeout(()=>el.remove(),2800)}
function setHeader(title,eye='CampusX · GCIT'){document.getElementById('pageTitle').textContent=title;document.getElementById('eyebrow').textContent=eye}
function updateBadges(){document.getElementById('pendingBadge').textContent=state.leave.filter(x=>x.status==='Pending').length;document.getElementById('gateBadge').textContent=state.gate.filter(x=>x.result==='Manual').length}
function pageHead(title,desc,action=''){return `<div class="page-head"><div><h2>${title}</h2><p>${desc}</p></div>${action}</div>`}
function stat(label,value,icon){return `<div class="stat"><span class="stat-icon">${icon}</span><div><strong>${value}</strong><span>${label}</span></div></div>`}
function leaveRows(rows=state.leave){return rows.map(x=>`<tr><td>${person(x.student,x.sid)}</td><td>${x.date}<br><small>${x.exit}–${x.return}</small></td><td>${x.destination}</td><td>${badge(x.status)}</td><td><div class="action-row">${x.status==='Pending'?`<button class="btn btn-primary" onclick="decide('${x.id}','Approved')">Approve</button><button class="btn btn-danger" onclick="decide('${x.id}','Rejected')">Reject</button>`:''}<button class="btn btn-outline" onclick="showLeave('${x.id}')">View</button></div></td></tr>`).join('')}
function dashboard(){setHeader('Good morning, Karma',new Date().toLocaleDateString('en-GB',{weekday:'long',day:'2-digit',month:'long'}));const outside=state.leave.filter(x=>['Outside','Overdue'].includes(x.status));content.innerHTML=`
 <div class="hero"><div><h2>Campus operations at a glance</h2><p>Monitor student movement, approvals and visitors in real time.</p></div><div class="mode-panel"><div><strong>${state.eventMode?'Event Mode active':'Normal Period'}</strong><span>${state.eventMode?'Every leave needs manual approval':'Rule-based approval enabled'}</span></div><button class="switch ${state.eventMode?'on':''}" onclick="toggleEvent()"><i></i></button></div></div>
 <div class="stats">${stat('Pending approvals',state.leave.filter(x=>x.status==='Pending').length,'▤')}${stat('Students outside',outside.length,'↗')}${stat('Visitors inside',state.visitors.filter(x=>x.status==='Inside').length,'♙')}${stat('Overdue students',state.leave.filter(x=>x.status==='Overdue').length,'!')}</div>
 <div class="quick-actions"><button class="quick" onclick="navigate('leave')"><span>✓</span><strong>Review requests</strong><small>Process pending leave</small></button><button class="quick" onclick="navigate('visitors');setTimeout(openVisitor,50)"><span>＋</span><strong>Register visitor</strong><small>Create visitor entry</small></button><button class="quick" onclick="navigate('gate')"><span>▣</span><strong>Resolve gate check</strong><small>Review face mismatch</small></button><button class="quick" onclick="exportCSV()"><span>⇩</span><strong>Export report</strong><small>Download movement CSV</small></button></div>
 <div class="grid-2"><div class="card"><div class="card-head"><div><h3>Recent leave requests</h3><p>Requests requiring administrative attention</p></div><button class="link-btn" onclick="navigate('leave')">View all →</button></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Schedule</th><th>Destination</th><th>Status</th><th>Action</th></tr></thead><tbody>${leaveRows(state.leave.slice(0,4))}</tbody></table></div></div>
 <div class="card"><div class="card-head"><div><h3>Live activity</h3><p>Latest system events</p></div></div><div class="activity">${state.activities.map(a=>`<div class="activity-item"><i class="dot"></i><div><strong>${a.title}</strong><p>${a.text}</p></div><time>${a.time}</time></div>`).join('')}</div></div></div>`}
function leavePage(){setHeader('Leave management');content.innerHTML=pageHead('Leave requests','Review, approve and track every student leave request.',`<button class="btn btn-orange" onclick="toggleEvent()">${state.eventMode?'Disable':'Enable'} Event Mode</button>`)+`<div class="toolbar"><label class="search-box">⌕ <input id="leaveSearch" placeholder="Search student or ID" oninput="filterLeave()"></label><select class="filter" id="leaveStatus" onchange="filterLeave()"><option>All statuses</option>${['Pending','Approved','Rejected','Outside','Returned','Overdue'].map(x=>`<option>${x}</option>`)}</select></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Student</th><th>Leave window</th><th>Destination</th><th>Status</th><th>Action</th></tr></thead><tbody id="leaveBody">${leaveRows()}</tbody></table></div></div>`}
function filterLeave(){const q=document.getElementById('leaveSearch').value.toLowerCase(),s=document.getElementById('leaveStatus').value;const rows=state.leave.filter(x=>(x.student.toLowerCase().includes(q)||x.sid.includes(q))&&(s==='All statuses'||x.status===s));document.getElementById('leaveBody').innerHTML=leaveRows(rows)||`<tr><td colspan="5" class="empty">No matching requests</td></tr>`}
function movementPage(){setHeader('Live movement');const rows=state.leave.filter(x=>['Outside','Overdue','Returned'].includes(x.status));content.innerHTML=pageHead('Student movement','Current campus exit and return status, updated from gate scans.')+`<div class="stats">${stat('Currently outside',rows.filter(x=>x.status==='Outside').length,'↗')}${stat('Overdue',rows.filter(x=>x.status==='Overdue').length,'!')}${stat('Returned today',rows.filter(x=>x.status==='Returned').length,'↙')}${stat('Approved exits',state.leave.filter(x=>x.status==='Approved').length,'✓')}</div><div class="card"><div class="table-wrap"><table><thead><tr><th>Student</th><th>Approved window</th><th>Destination</th><th>Movement status</th><th>Action</th></tr></thead><tbody>${leaveRows(rows)}</tbody></table></div></div>`}
function gatePage(){setHeader('Gate verification');content.innerHTML=pageHead('Gate verification','Review ID and face verification outcomes requiring staff intervention.')+`<div class="grid-2"><div class="card"><div class="card-head"><div><h3>Verification log</h3><p>Latest gate scan results</p></div></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Direction</th><th>Confidence</th><th>Result</th><th>Action</th></tr></thead><tbody>${state.gate.map(x=>`<tr><td>${person(x.student,x.sid)}</td><td>${x.direction}<br><small>${x.time}</small></td><td>${x.confidence}</td><td>${badge(x.result)}</td><td>${x.result==='Manual'?`<button class="btn btn-primary" onclick="resolveGate('${x.id}',true)">Grant</button> <button class="btn btn-danger" onclick="resolveGate('${x.id}',false)">Deny</button>`:'—'}</td></tr>`).join('')}</tbody></table></div></div><div class="card alert-card"><div class="card-head"><div><h3>Verification policy</h3><p>Fallback protocol for uncertain matches</p></div></div><div class="activity"><div class="activity-item"><i class="dot"></i><div><strong>Approved leave required</strong><p>Student must have a valid leave window.</p></div></div><div class="activity-item"><i class="dot"></i><div><strong>ID and face match</strong><p>Below-threshold results need staff review.</p></div></div><div class="activity-item"><i class="dot"></i><div><strong>Every decision is logged</strong><p>Manual overrides are retained in the audit trail.</p></div></div></div></div></div>`}
function visitorsPage(){setHeader('Visitor management');content.innerHTML=pageHead('Family & visitors','Register, verify and check out campus visitors.',`<button class="btn btn-primary" onclick="openVisitor()">＋ Register visitor</button>`)+`<div class="stats">${stat('Inside now',state.visitors.filter(x=>x.status==='Inside').length,'♙')}${stat('Visits today',state.visitors.length,'▤')}${stat('Checked out',state.visitors.filter(x=>x.status!=='Inside').length,'✓')}${stat('Awaiting verification',0,'?')}</div><div class="card"><div class="table-wrap"><table><thead><tr><th>Visitor</th><th>Visiting student</th><th>Relationship / purpose</th><th>Entry / exit</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.visitors.map(v=>`<tr><td>${person(v.name,v.phone)}</td><td>${v.student}<br><small>${v.sid}</small></td><td>${v.relation}<br><small>${v.purpose}</small></td><td>${v.entry} / ${v.exit}</td><td>${badge(v.status)}</td><td>${v.status==='Inside'?`<button class="btn btn-orange" onclick="checkout('${v.id}')">Check out</button>`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
function studentsPage(){setHeader('Student directory');const unique=[...new Map(state.leave.map(x=>[x.sid,x])).values()];content.innerHTML=pageHead('Registered students','Manage leave profiles and view current campus status.')+`<div class="toolbar"><label class="search-box">⌕ <input placeholder="Search student records"></label><button class="btn btn-primary" onclick="toast('Student import template ready')">＋ Add student</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Student</th><th>Programme</th><th>Current status</th><th>Latest request</th><th>Profile</th></tr></thead><tbody>${unique.map(x=>`<tr><td>${person(x.student,x.sid)}</td><td>${x.course}</td><td>${badge(['Outside','Overdue'].includes(x.status)?x.status:'Inside')}</td><td>${x.id}</td><td><button class="btn btn-outline" onclick="showLeave('${x.id}')">View record</button></td></tr>`).join('')}</tbody></table></div></div>`}
function reportsPage(){setHeader('Reports & audit');content.innerHTML=pageHead('Reports & audit trail','Export operational records and review accountable system actions.',`<button class="btn btn-primary" onclick="exportCSV()">⇩ Export CSV</button>`)+`<div class="report-cards"><div class="card report"><span class="stat-icon">▤</span><h3>Leave summary</h3><p>Approval outcomes, reasons, destinations and punctual returns.</p><button class="btn btn-light" onclick="exportCSV('leave')">Download</button></div><div class="card report"><span class="stat-icon">↔</span><h3>Movement register</h3><p>Verified exit, return, duration and overdue records.</p><button class="btn btn-light" onclick="exportCSV('movement')">Download</button></div><div class="card report"><span class="stat-icon">♙</span><h3>Visitor log</h3><p>Visitor identity, host student, purpose and campus duration.</p><button class="btn btn-light" onclick="exportCSV('visitor')">Download</button></div></div><div class="grid-2" style="margin-top:18px"><div class="card"><div class="card-head"><div><h3>Leave volume · this week</h3><p>Daily submitted requests</p></div></div><div class="bar-chart">${[['Mon',56],['Tue',78],['Wed',42],['Thu',88],['Fri',67],['Sat',28],['Sun',19]].map(x=>`<div class="bar-col"><div class="bar" style="height:${x[1]}%"></div><span>${x[0]}</span></div>`).join('')}</div></div><div class="card"><div class="card-head"><div><h3>Administrative audit</h3><p>Recent staff decisions</p></div></div><div class="activity">${state.activities.map(a=>`<div class="activity-item"><i class="dot"></i><div><strong>${a.title}</strong><p>${a.text}</p></div><time>${a.time}</time></div>`).join('')}</div></div></div>`}
function settingsPage(){setHeader('System settings');content.innerHTML=pageHead('Settings','Configure approval rules, notifications and access control.')+`<div class="settings-grid"><div class="card setting"><h3>Automatic approvals</h3><p>Allow standard requests to be approved by configured rules during normal periods.</p><div class="setting-line"><span>Rule-based approval</span><button class="switch ${!state.eventMode?'on':''}" onclick="toggleEvent()"><i></i></button></div></div><div class="card setting"><h3>Overdue alerts</h3><p>Notify wardens when the expected return time passes.</p><div class="setting-line"><span>Email and dashboard alerts</span><button class="switch on" onclick="this.classList.toggle('on');toast('Alert preference saved')"><i></i></button></div></div><div class="card setting"><h3>Face verification</h3><p>Send confidence scores below 75% for manual gate review.</p><div class="setting-line"><span>Manual fallback threshold</span><strong>75%</strong></div></div><div class="card setting danger-zone"><h3>Reset prototype records</h3><p>Restore the original demonstration dataset on this device.</p><div class="setting-line"><span>Local prototype data</span><button class="btn btn-danger" onclick="resetData()">Reset data</button></div></div></div>`}
const pages={dashboard,leave:leavePage,movement:movementPage,gate:gatePage,visitors:visitorsPage,students:studentsPage,reports:reportsPage,settings:settingsPage};
function navigate(p){currentPage=p;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));pages[p]();document.getElementById('sidebar').classList.remove('open');location.hash=p}
function toggleEvent(){state.eventMode=!state.eventMode;save();toast(state.eventMode?'Event Mode enabled — manual approval required':'Normal Period restored');pages[currentPage]()}
function decide(id,status){const x=state.leave.find(x=>x.id===id);x.status=status;state.activities.unshift({title:`Leave ${status.toLowerCase()}`,text:`${x.student} · ${x.sid}`,time:'Just now'});save();updateBadges();toast(`${x.id} ${status.toLowerCase()}`);pages[currentPage]()}
function resolveGate(id,grant){const x=state.gate.find(x=>x.id===id);x.result=grant?'Granted':'Denied';state.activities.unshift({title:`Manual access ${grant?'granted':'denied'}`,text:`${x.student} · ${x.sid}`,time:'Just now'});save();updateBadges();toast(`Gate access ${grant?'granted':'denied'}`,!grant);gatePage()}
function checkout(id){const v=state.visitors.find(x=>x.id===id);v.status='Checked out';v.exit=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});save();toast(`${v.name} checked out`);visitorsPage()}
function showLeave(id){const x=state.leave.find(x=>x.id===id);modal(`<div class="modal-head"><h3>${x.id} · Leave details</h3><button onclick="closeModal()">×</button></div><div class="modal-body"><div class="detail-grid"><div class="detail"><span>Student</span><strong>${x.student} · ${x.sid}</strong></div><div class="detail"><span>Programme</span><strong>${x.course}</strong></div><div class="detail"><span>Leave window</span><strong>${x.date}, ${x.exit}–${x.return}</strong></div><div class="detail"><span>Status</span>${badge(x.status)}</div><div class="detail"><span>Destination</span><strong>${x.destination}</strong></div><div class="detail"><span>Reason</span><strong>${x.reason}</strong></div></div><div class="timeline"><div><strong>Request submitted</strong><p>Student profile and leave information validated.</p></div><div><strong>Approval status · ${x.status}</strong><p>Last updated in the centralized leave register.</p></div></div></div><div class="modal-foot">${x.status==='Pending'?`<button class="btn btn-danger" onclick="closeModal();decide('${x.id}','Rejected')">Reject</button><button class="btn btn-primary" onclick="closeModal();decide('${x.id}','Approved')">Approve</button>`:`<button class="btn btn-outline" onclick="closeModal()">Close</button>`}</div>`)}
function openVisitor(){modal(`<div class="modal-head"><h3>Register new visitor</h3><button onclick="closeModal()">×</button></div><form id="visitorForm" onsubmit="addVisitor(event)"><div class="visitor-form"><div class="field"><label>Visitor name</label><input name="name" required></div><div class="field"><label>Phone number</label><input name="phone" required></div><div class="field"><label>Student name</label><input name="student" required></div><div class="field"><label>Student ID</label><input name="sid" required></div><div class="field"><label>Relationship</label><select name="relation"><option>Parent</option><option>Guardian</option><option>Sibling</option><option>Friend</option><option>Other</option></select></div><div class="field"><label>Purpose</label><input name="purpose" required></div><div class="field full"><label>Identity verification note</label><textarea name="note" placeholder="ID type or staff verification note"></textarea></div></div><div class="modal-foot"><button type="button" class="btn btn-outline" onclick="closeModal()">Cancel</button><button class="btn btn-primary">Verify & check in</button></div></form>`)}
function addVisitor(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.visitors.unshift({id:`VS-${320+state.visitors.length}`,name:d.name,phone:d.phone,student:d.student,sid:d.sid,relation:d.relation,purpose:d.purpose,entry:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),exit:'—',status:'Inside'});save();closeModal();toast('Visitor verified and checked in');visitorsPage()}
function modal(html){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`}function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function exportCSV(type='all'){let rows=[['Type','ID','Name','Reference','Status']];if(type==='all'||type==='leave'||type==='movement')state.leave.forEach(x=>rows.push(['Leave',x.id,x.student,x.sid,x.status]));if(type==='all'||type==='visitor')state.visitors.forEach(x=>rows.push(['Visitor',x.id,x.name,x.sid,x.status]));const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`campusx-${type}-report.csv`;a.click();URL.revokeObjectURL(a.href);toast('Report downloaded')}
function resetData(){state=structuredClone(initialState);save();updateBadges();toast('Prototype data restored');settingsPage()}
document.getElementById('mainNav').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)navigate(b.dataset.page)});document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('notificationBtn').onclick=()=>toast(`${state.leave.filter(x=>x.status==='Pending').length} approvals and ${state.gate.filter(x=>x.result==='Manual').length} gate review pending`);document.getElementById('logoutBtn').onclick=()=>toast('Prototype session secured');document.getElementById('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){navigate('leave');document.getElementById('leaveSearch').value=e.target.value;filterLeave()}});window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(pages[p]&&p!==currentPage)navigate(p)});updateBadges();navigate(location.hash.slice(1) in pages?location.hash.slice(1):'dashboard');
